name: Deploy to environment
description: Deploys to specific environment

inputs:
    sfdx_auth_url:
        description: "The auth url tied to your deployment environment"
        required: true

runs:
    using: "composite"
    steps:
        - name: Install SFDX
          shell: bash
          run: |
              npm install --global @salesforce/cli
        - name: Login To Org
          shell: bash
          run: |
              sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.sfdx_auth_url }}")
        - name: Generate package.xml
          shell: bash
          run: |
              sf project generate manifest -p force-app -d manifest
        - name: Deploy to ${{ inputs.sfdx_auth_url }}
          shell: bash
          run: |
              deployFlags=(
                  --manifest manifest/package.xml
                  --wait 30
                  --test-level RunLocalTests
                  --verbose
                )
              if [ "${{ inputs.validateOnly }}" = "true" ]; then
                deployFlags+=( --dry-run )
              fi
              sf project deploy start "${deployFlags[@]}"
