name: Automated Run Test Classes

on:
  push:
    paths:
      - force-app/**

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test in sandbox
        uses: ./.github/actions/run-test
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_SANDBOX }}
