name: Manual Deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Select the environment to run the test
                options:
                    - sandbox
                    - production
                default: "sandbox"
                required: true

jobs:
    run-in-sandbox:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs.environment == 'sandbox' }}
        steps:
            - uses: actions/checkout@v3
            - name: Deploy to sandbox
              uses: ./.github/actions/deploy
              with:
                  sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_SANDBOX }}

    run-in-prod:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs.environment == 'production' }}
        steps:
            - uses: actions/checkout@v3
            - name: Deploy to production
              uses: ./.github/actions/deploy
              with:
                  sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_PRODUCTION }}
