name: Manual Run Test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to
        options:
          - sandbox
          - production
        default: "partial-sandbox"
        required: true
      validateOnly:
        description: "Run the deployment as validation only"
        type: boolean
        default: false

jobs:
  deploy-partial-sandbox:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./.github/actions/run-test
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_SANDBOX }}

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'production' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        uses: ./.github/actions/run-test
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_PRODUCTION }}
